### ISSUE TITLE
`charmcraft init` creates broken charm

### ISSUE THREAD

**Issue by hatched** [canonical/charmcraft#238]
It looks like the install hook expects an action to exist? 

To reproduce:
- run `charmcraft init`
- change the series in `metadata.yaml` to `focal`
- `charmcraft build`
- deploy the charm

```
juju-dashboard-charm-0: 16:21:17 INFO juju.worker.uniter awaiting error resolution for "install" hook
juju-dashboard-charm-0: 16:21:17 INFO unit.juju-dashboard-charm/0.juju-log Running legacy hooks/install.
juju-dashboard-charm-0: 16:21:17 ERROR unit.juju-dashboard-charm/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 46, in <module>
    main(JujuDashboardCharmCharm)
  File "/var/lib/juju/agents/juju-dashboard-charm-0/charm/venv/ops/main.py", line 390, in main
    charm = charm_class(framework)
  File "./src/charm.py", line 24, in __init__
    self.framework.observe(self.on.fortune_action, self._on_fortune_action)
AttributeError: 'CharmEvents' object has no attribute 'fortune_action'
juju-dashboard-charm-0: 16:21:17 ERROR juju.worker.uniter.operation hook "install" (via hook dispatching script: dispatch) failed: exit status 1
juju-dashboard-charm-0: 16:21:17 INFO juju.worker.uniter awaiting error resolution for "install" hook
juju-dashboard-charm-0: 16:22:36 INFO juju.worker.uniter awaiting error resolution for "install" hook
juju-dashboard-charm-0: 16:22:36 INFO unit.juju-dashboard-charm/0.juju-log Running legacy hooks/install.
juju-dashboard-charm-0: 16:22:36 ERROR unit.juju-dashboard-charm/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 46, in <module>
    main(JujuDashboardCharmCharm)
  File "/var/lib/juju/agents/juju-dashboard-charm-0/charm/venv/ops/main.py", line 390, in main
    charm = charm_class(framework)
  File "./src/charm.py", line 24, in __init__
    self.framework.observe(self.on.fortune_action, self._on_fortune_action)
AttributeError: 'CharmEvents' object has no attribute 'fortune_action'
juju-dashboard-charm-0: 16:22:37 ERROR juju.worker.uniter.operation hook "install" (via hook dispatching script: dispatch) failed: exit status 1
juju-dashboard-charm-0: 16:22:37 INFO juju.worker.uniter awaiting error resolution for "install" hook
```

**Comment by mthaddon** [comment]
This seems to have been introduced with https://github.com/canonical/charmcraft/commit/ece6cdbf69883702b55ce9aeba2e2fd0e6e7e6d9. Per the comments in `./src/charm.py`:

    # Note: you need to uncomment the example in the actions.yaml file for this to work (ensure
    # to not just leave the example, but adapt to your needs for actions commands)

Possibly this should be added to the TODO output that's printed after you run `charmcraft init` to make it clearer to users?

**Comment by jameinel** [comment]
I would say that if the action is commented out the observe code as well.

John
=:->

**Comment by tomwardill** [comment]
Adding that this is also a problem after https://github.com/canonical/charmcraft/issues/243 is fixed.
The out of the box tests will fail.

**Comment by facundobatista** [comment]
Just wrote #247 about the future of `init` and tests, which will improve this situation.
